name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #       with:
  #         path: "${{ github.repository }}"
  #     - name: Lint Ansible Playbook
  #       # replace "master" with any valid ref
  #       uses: ansible/ansible-lint-action@master
  #       with:
  #         targets: ""
  #         override-deps: |
  #           ansible==2.9
  #           ansible-lint==4.2.0
  #         args: ""
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release